# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://claycurran0.github.io/'
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:              
  name:              Clay Curran
  url:               https://twitter.com/yayitsclay
  email:             claycurran1@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
